# Generated by Django 5.2.11 on 2026-04-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(help_text='Define a hierarquia da faixa para ordenação na tela')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('link_google_maps', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='logos_academias/')),
                ('responsavel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_atletas/')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='core.academia')),
                ('faixa_atual', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='atletas_atuais', to='core.faixa')),
                ('modalidades', models.ManyToManyField(related_name='atletas', to='core.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_graduacao', models.DateField()),
                ('examinador', models.CharField(help_text='Quem aplicou o exame', max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_faixas', to='core.atleta')),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.faixa')),
            ],
            options={
                'ordering': ['-data_graduacao'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='midias_galeria/')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('academia_autora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academia')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidade')),
            ],
        ),
    ]
