# Generated by Django 5.2.11 on 2026-04-08 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(help_text='Texto curto para a página inicial', max_length=300)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PedidoAfiliacaoAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_academia', models.CharField(max_length=200)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('termo_lgpd', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], default='P', max_length=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('observacoes_admin', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='academia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_academias/'),
        ),
        migrations.CreateModel(
            name='PedidoAfiliacaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('termo_lgpd', models.BooleanField(default=False, help_text='Aceitou os termos de uso dos dados')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], default='P', max_length=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('observacoes_admin', models.TextField(blank=True, help_text='Anotações internas da diretoria')),
                ('academia_desejada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academia')),
                ('modalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modalidade')),
            ],
        ),
    ]
