# Generated by Django 5.2.11 on 2026-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_pedidoafiliacaoacademia_alter_academia_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_evento', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
            options={
                'ordering': ['data_evento'],
            },
        ),
    ]
