# Generated by Django 5.2.11 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atleta_usuario_alter_atleta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoafiliacaoatleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_fotos/'),
        ),
    ]
