# Generated by Django 5.2.11 on 2026-05-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedidoafiliacaoatleta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='core.academia'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='faixa_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atletas_atuais', to='core.faixa'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='modalidades',
            field=models.ManyToManyField(blank=True, related_name='atletas', to='core.modalidade'),
        ),
    ]
