# Generated by Django 5.2.11 on 2026-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academia_ativo_atleta_ativo_alter_atleta_academia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='cor_hex',
            field=models.CharField(default='#FFFFFF', help_text='Cor da faixa em hexadecimal (ex: #000000)', max_length=7),
        ),
    ]
