# Generated by Django 5.2.11 on 2026-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faixa_cor_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='dan_atual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dan (Se faixa preta)'),
        ),
        migrations.AddField(
            model_name='faixa',
            name='is_preta',
            field=models.BooleanField(default=False, verbose_name='É Faixa Preta?'),
        ),
        migrations.AddField(
            model_name='historicograduacao',
            name='dan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dan'),
        ),
    ]
