# Generated by Django 5.2.11 on 2026-06-04 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_atleta_dan_atual_faixa_is_preta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='modalidades',
            field=models.ManyToManyField(blank=True, related_name='academias', to='core.modalidade'),
        ),
        migrations.AddField(
            model_name='academia',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='academias_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academia',
            name='responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academia_antiga', to=settings.AUTH_USER_MODEL),
        ),
    ]
