# Generated by Django 5.2.11 on 2026-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_academia_modalidades_academia_professores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Nome do Mestre Responsável', max_length=200),
        ),
    ]
