# Generated by Django 5.2.11 on 2026-06-18 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicograduacao',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modalidade'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='dan_atual',
            field=models.IntegerField(blank=True, help_text='Dan Principal (LEGACY)', null=True, verbose_name='Dan (Se faixa preta)'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='faixa_atual',
            field=models.ForeignKey(blank=True, help_text='Faixa Principal (LEGACY)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atletas_atuais', to='core.faixa'),
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dan', models.IntegerField(blank=True, null=True, verbose_name='Dan (Se faixa preta)')),
                ('data_graduacao', models.DateField(default=django.utils.timezone.now)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes', to='core.atleta')),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.faixa')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'unique_together': {('atleta', 'modalidade')},
            },
        ),
    ]
