# Generated by Django 5.2.11 on 2026-06-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicograduacao_modalidade_alter_atleta_dan_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='core.modalidade'),
        ),
    ]
