# Generated by Django 5.2.11 on 2026-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_faixa_modalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faixa',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='modalidade',
            name='faixas',
            field=models.ManyToManyField(blank=True, related_name='modalidades', to='core.faixa'),
        ),
    ]
